# 넘파이 예시

## 객체 속성 및 인덱싱

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = a.astype(float)

In [11]:
b.dtype

dtype('float64')

In [12]:
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
a[2, 3]

13

In [15]:
a[1, 0:5]

array([5, 6, 7, 8, 9])

In [16]:
a[:, 1]

array([ 1,  6, 11])

In [17]:
a[1:3, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a = np.array([20, 30, 40, 50])

In [20]:
b = np.arange(4)

In [21]:
b

array([0, 1, 2, 3])

In [22]:
c = a - b

In [23]:
c

array([20, 29, 38, 47])

In [24]:
b ** 2

array([0, 1, 4, 9])

In [25]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [26]:
a < 35

array([ True,  True, False, False])

In [27]:
A = np.array([[1, 1], [0, 1]])

In [28]:
B = np.array([[2, 0], [3, 4]])

In [29]:
A * B

array([[2, 0],
       [0, 4]])

In [30]:
A @ B

array([[5, 4],
       [3, 4]])

In [31]:
A.dot(B)

array([[5, 4],
       [3, 4]])

## 주요 함수

In [32]:
np.set_printoptions(precision=4)

In [33]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [35]:
a = a.reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
a.sum(), a.min(), a.max()

(15, 0, 5)

In [37]:
a.sum(axis=0)

array([3, 5, 7])

In [38]:
a.sum(axis=1)

array([ 3, 12])

In [39]:
a.cumsum(axis=0)

array([[0, 1, 2],
       [3, 5, 7]])

In [40]:
np.random.seed(42)

In [41]:
b = np.random.rand(2, 3)

In [42]:
b

array([[0.3745, 0.9507, 0.732 ],
       [0.5987, 0.156 , 0.156 ]])

In [43]:
np.concatenate([a, b])

array([[0.    , 1.    , 2.    ],
       [3.    , 4.    , 5.    ],
       [0.3745, 0.9507, 0.732 ],
       [0.5987, 0.156 , 0.156 ]])

In [44]:
np.concatenate([a, b], axis=1)

array([[0.    , 1.    , 2.    , 0.3745, 0.9507, 0.732 ],
       [3.    , 4.    , 5.    , 0.5987, 0.156 , 0.156 ]])

In [45]:
np.stack([a, b]).shape

(2, 2, 3)

In [46]:
np.vstack([a, b]).shape

(4, 3)

In [47]:
np.hstack([a, b]).shape

(2, 6)

In [48]:
np.corrcoef(b)

array([[ 1.    , -0.9266],
       [-0.9266,  1.    ]])

In [49]:
np.exp(a)

array([[  1.    ,   2.7183,   7.3891],
       [ 20.0855,  54.5982, 148.4132]])

In [50]:
np.log(np.exp(a))

array([[0., 1., 2.],
       [3., 4., 5.]])

In [51]:
np.sqrt(a)

array([[0.    , 1.    , 1.4142],
       [1.7321, 2.    , 2.2361]])

In [52]:
np.square(np.sqrt(a))

array([[0., 1., 2.],
       [3., 4., 5.]])